# side settings
## title
title: Clean Blog
hometitle: Articles   # 不可过长
url: "https://crqblog.github.io"
## 看版娘
## nav
nav:
- name: Home
  link: /
- name: About
  link: /about
## Theme
theme: jekyll-theme-cayman
