# side settings
## title
title: Clean Blog
hometitle: Articles   # 不可过长
url: "https://crqblog.github.io"
## 组件
navbarcolor: black ## 导航栏颜色设置，可以用16进制色或英文
headcolor: grey ## 头部主题颜色设置，不可以用16进制色，只可以英文
## 看版娘
## nav
nav:
- name: Home
  link: /
- name: About
  link: /about
## Theme
theme: jekyll-theme-cayman
